# 모델 설정
models:
  qwen_path: "Qwen/Qwen3-32B-AWQ"
  kobart_path: "digit82/kobart-summarization"
  offload_folder: "./offload"

# 생성 파라미터
generation:
  kobart:
    max_length: 600
    num_beams: 4
    early_stopping: true
  qwen:
    max_new_tokens: 2048
    temperature: 0.1

# 처리 파라미터
processing:
  stride: 700
  max_input_tokens: null  # null이면 tokenizer.model_max_length 사용

# 파일 경로
files:
  input_jsonl: "250724_data2_input_sk.jsonl"
  output_txt: "250724_data2_output_sk.txt"

# 프롬프트 템플릿
prompts:
  kobart_compression: |
    다음은 회의 기록의 일부분이야. 회의정보 압축 전문가로서
    1. 회의 텍스트의 발언자와 발언내용을 보고 핵심 의미를 보존을 최우선하면서, 정보 소실이 없게 문장과 단어의 수를 가능한 한 줄여 압축해주세요. 
    2. 불필요한 수식어, 반복, 예시는 생략하고, 문장 간 중복도 최대한 제거해주세요.
    3. 압축된 내용을 정리하고 '발언자': '발언내용' 형식으로 작성하세요.
  
  qwen_summary_template: |
    다음은 회의 내용 일부입니다:

    [회의 내용]
    {content}

    1. 이 회의 내용을 요약해줘.
    2. 안건이 있다면 리스트로 정리해줘.
    3. 각 안건에 대해 필요한 작업들을 분해해줘. (누가, 무엇을, 언제까지)

    결과는 아래 형식으로 줘:

    ### 요약
    - ...

    ### 안건
    1. 제목: ...
       - 세부 설명
       - 관련 발언자

    ### 업무 분해
    - [업무]: 담당자, 마감일, 관련 안건

  qwen_chunk_template: |
    다음은 회의의 일부입니다.

    [회의 내용]
    {chunk}

    [이전까지의 압축내용]
    {summary_accum}

    1. 이 회의 내용을 요약해줘.
    2. 안건이 있다면 리스트로 정리해줘.
    3. 각 안건에 대해 필요한 작업들을 분해해줘. (누가, 무엇을, 언제까지)

    결과는 아래 형식으로 줘:

    ### 요약
    - ...

    ### 안건
    1. 제목: ...
       - 세부 설명
       - 관련 발언자

    ### 업무 분해
    - [업무]: 담당자, 마감일, 관련 안건